# Generated by Django 2.2.13 on 2021-03-12 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(default='scanner@email.com', max_length=255, unique=True)),
                ('name', models.CharField(default='Media Scanner', max_length=20)),
                ('organisation', models.CharField(default='Media Scanner', max_length=20)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PCOSModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing', models.DateTimeField(auto_now_add=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('Chin', models.IntegerField(blank=True, null=True)),
                ('Cheeks', models.IntegerField(blank=True, null=True)),
                ('Lips', models.IntegerField(blank=True, null=True)),
                ('Breast', models.IntegerField(blank=True, null=True)),
                ('Arms', models.IntegerField(blank=True, null=True)),
                ('Thigh', models.IntegerField(blank=True, null=True)),
                ('Exercise', models.IntegerField(blank=True, null=True)),
                ('Eat', models.IntegerField(blank=True, null=True)),
                ('PCOS', models.CharField(max_length=100)),
                ('BMI', models.CharField(max_length=100)),
                ('Weight', models.CharField(max_length=100)),
                ('Period', models.CharField(max_length=100)),
                ('Concieve', models.CharField(max_length=100)),
                ('Skin', models.CharField(max_length=100)),
                ('Hairthin', models.CharField(max_length=100)),
                ('Patch', models.CharField(max_length=100)),
                ('Tired', models.CharField(max_length=100)),
                ('Mood', models.CharField(max_length=100)),
                ('Can', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('report', jsonfield.fields.JSONField(verbose_name={})),
                ('developer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
