# Generated by Django 2.2.13 on 2021-03-13 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CervicalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing', models.DateTimeField(auto_now_add=True)),
                ('age', models.FloatField(blank=True, null=True)),
                ('no_of_sexual_parteners', models.FloatField(blank=True, null=True)),
                ('age_of_first_intercourse', models.FloatField(blank=True, null=True)),
                ('no_of_pregnancies', models.FloatField(blank=True, null=True)),
                ('smokes', models.FloatField(blank=True, null=True)),
                ('smokes_packs', models.FloatField(blank=True, null=True)),
                ('hormonal_contraceptives', models.FloatField(blank=True, null=True)),
                ('intra_uterine', models.FloatField(blank=True, null=True)),
                ('STDS', models.FloatField(blank=True, null=True)),
                ('any_std', models.FloatField(blank=True, null=True)),
                ('condylomatosis', models.FloatField(blank=True, null=True)),
                ('cervical_condylomatosis', models.FloatField(blank=True, null=True)),
                ('vaginal', models.FloatField(blank=True, null=True)),
                ('vulvo_perineal', models.FloatField(blank=True, null=True)),
                ('syphilis', models.FloatField(blank=True, null=True)),
                ('pelvic', models.FloatField(blank=True, null=True)),
                ('genital', models.FloatField(blank=True, null=True)),
                ('molluscum', models.FloatField(blank=True, null=True)),
                ('AIDS', models.FloatField(blank=True, null=True)),
                ('HIV', models.FloatField(blank=True, null=True)),
                ('hepatitis', models.FloatField(blank=True, null=True)),
                ('HPV', models.FloatField(blank=True, null=True)),
                ('diagnosis_std', models.FloatField(blank=True, null=True)),
                ('cancer', models.FloatField(blank=True, null=True)),
                ('neoplasis', models.FloatField(blank=True, null=True)),
                ('diagnosis_hpv', models.FloatField(blank=True, null=True)),
                ('report', jsonfield.fields.JSONField(verbose_name={})),
                ('developer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
